#!/usr/bin/env bash
set -euo pipefail

MODEL_NAME=${MODEL_NAME:-BAAI/bge-m3}
MAX_TOKEN_LENGTH=${MAX_TOKEN_LENGTH:-256}
BATCH_SIZE=${BATCH_SIZE:-16}
DEVICE=${DEVICE:-cuda}
GPU_DEVICES=${GPU_DEVICES:-0,1,2,3}
HOST=${HOST:-0.0.0.0}
PORT=${PORT:-8001}

export MODEL_NAME MAX_TOKEN_LENGTH BATCH_SIZE DEVICE GPU_DEVICES

PYTHONPATH=src uvicorn gpu_service.main:app --host "$HOST" --port "$PORT"
